<?php
/**
 * BMET EC Card Manager — one-time installer.
 * Connects the MySQL database, creates the tables and the admin credentials,
 * then writes admin/includes/config.php.
 *
 * Upload the whole project to cPanel (public_html), open  /install.php  once,
 * fill the form, and DELETE THIS FILE after a successful installation.
 */
error_reporting(E_ALL);
ini_set('display_errors', '1');
date_default_timezone_set('UTC');

$root = __DIR__;
$config_file = $root . '/admin/includes/config.php';
$installed = is_file($config_file);

$errors = [];
$done = false;
$in = [
    'driver' => 'mysql', 'host' => 'localhost', 'port' => '3306',
    'name' => '', 'user' => '', 'pass' => '',
    'admin_user' => 'admin', 'admin_email' => '', 'admin_pass' => '', 'admin_pass2' => '',
    'base_url' => '',
];

$checks = [
    'PHP 7.4+' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'PDO extension' => extension_loaded('pdo'),
    'PDO MySQL driver' => extension_loaded('pdo_mysql'),
    'GD extension (photo handling)' => extension_loaded('gd'),
    'admin/includes writable' => is_writable($root . '/admin/includes'),
    'project root writable' => is_writable($root),
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    foreach ($in as $k => $_v) if (isset($_POST[$k])) $in[$k] = trim((string)$_POST[$k]);

    if ($in['driver'] === 'mysql' && $in['name'] === '') $errors[] = 'Database name is required.';
    if ($in['driver'] === 'mysql' && $in['user'] === '') $errors[] = 'Database user is required.';
    if ($in['admin_user'] === '') $errors[] = 'Admin username is required.';
    if (strlen($in['admin_pass']) < 6) $errors[] = 'Admin password must be at least 6 characters.';
    if ($in['admin_pass'] !== $in['admin_pass2']) $errors[] = 'Admin passwords do not match.';

    if (!$errors) {
        try {
            if ($in['driver'] === 'sqlite') {
                $dir = $root . '/admin/data';
                if (!is_dir($dir)) mkdir($dir, 0775, true);
                $pdo = new PDO('sqlite:' . $dir . '/app.sqlite');
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            } else {
                $dsn = sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $in['host'], (int)$in['port'], $in['name']);
                $pdo = new PDO($dsn, $in['user'], $in['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            }
            require_once $root . '/admin/includes/db.php';
            foreach (ec_schema_sql($in['driver']) as $sql) $pdo->exec($sql);

            // admin account
            $st = $pdo->prepare('SELECT id FROM admins WHERE username = ?');
            $st->execute([$in['admin_user']]);
            $hash = password_hash($in['admin_pass'], PASSWORD_DEFAULT);
            if ($st->fetch()) {
                $pdo->prepare('UPDATE admins SET password_hash = ?, email = ? WHERE username = ?')
                    ->execute([$hash, $in['admin_email'], $in['admin_user']]);
            } else {
                $pdo->prepare('INSERT INTO admins (username, email, password_hash) VALUES (?, ?, ?)')
                    ->execute([$in['admin_user'], $in['admin_email'], $hash]);
            }

            // base url
            $base = $in['base_url'];
            if ($base === '') {
                $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
                $base = $scheme . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost');
                $dir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/install.php'));
                $base .= rtrim($dir, '/');
            }
            $base = rtrim($base, '/');

            $cfg = [
                'driver' => $in['driver'],
                'host' => $in['host'],
                'port' => (int)$in['port'],
                'name' => $in['name'],
                'user' => $in['user'],
                'pass' => $in['pass'],
                'base_url' => $base,
                'installed_at' => date('c'),
            ];
            if ($in['driver'] === 'sqlite') $cfg['sqlite_path'] = $root . '/admin/data/app.sqlite';
            $php = "<?php\n/* Generated by install.php on " . date('c') . " — do not edit by hand unless you know what you are doing. */\nreturn " . var_export($cfg, true) . ";\n";
            if (@file_put_contents($config_file, $php) === false) throw new Exception('Could not write ' . $config_file);
            @chmod($config_file, 0644);

            @mkdir($root . '/ec-card/uploads', 0775, true);
            @mkdir($root . '/ec-card/verify', 0775, true);
            @mkdir($root . '/ec-card/enrollment-card', 0775, true);

            $done = true;
        } catch (Exception $e) {
            $errors[] = 'Installation failed: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Installer · BMET EC Card Manager</title>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="admin/assets/admin.css" />
</head>
<body>
<div class="adm-topbar">
  <div class="adm-topbar-inner">
    <span class="adm-brand"><strong>BMET EC Card Manager — Installer</strong></span>
    <span class="adm-user">PHP <?php echo PHP_VERSION; ?></span>
  </div>
</div>
<div class="adm-body" style="max-width:760px;">

<?php if ($done): ?>
  <div class="adm-card">
    <h2 style="color:#155724;">&#10004; Installation complete</h2>
    <p class="adm-sub">Database tables and the administrator account were created, and <code>admin/includes/config.php</code> was written.</p>
    <div class="alert alert-warn">
      For security, <b>delete <code>install.php</code> from your hosting now</b> (cPanel File Manager or FTP).
    </div>
    <p><a class="btn btn-primary" href="admin/login.php"><i class="fas fa-sign-in-alt"></i> Go to admin login</a></p>
  </div>
<?php else: ?>

  <?php if ($installed): ?>
    <div class="alert alert-warn">
      The system is already installed (<code>admin/includes/config.php</code> exists).
      Re-running the installer will <b>overwrite the configuration</b> and reset the admin password.
    </div>
  <?php endif; ?>

  <div class="adm-card">
    <h2>Server requirements</h2>
    <p class="adm-sub">Everything below must pass before installing.</p>
    <table class="adm-table">
      <?php foreach ($checks as $label => $ok): ?>
        <tr><td><?php echo $ok ? '✅' : '❌'; ?></td><td><?php echo htmlspecialchars($label); ?></td><td><?php echo $ok ? 'OK' : 'MISSING'; ?></td></tr>
      <?php endforeach; ?>
    </table>
  </div>

  <?php if ($errors): ?>
    <div class="alert alert-err"><?php foreach ($errors as $e) echo htmlspecialchars($e) . '<br>'; ?></div>
  <?php endif; ?>

  <form method="post" action="install.php" novalidate>
    <div class="adm-card">
      <h2>1 · Database connection</h2>
      <p class="adm-sub">Create the database first in cPanel → MySQL Databases, then enter its name, user and password here (on Hostinger the host is usually <code>localhost</code>).</p>
      <div class="form-grid">
        <div class="form-group"><label class="form-label">Driver</label>
          <select class="form-control" name="driver">
            <option value="mysql" <?php echo $in['driver'] === 'mysql' ? 'selected' : ''; ?>>MySQL / MariaDB (recommended)</option>
            <option value="sqlite" <?php echo $in['driver'] === 'sqlite' ? 'selected' : ''; ?>>SQLite (local testing only)</option>
          </select></div>
        <div class="form-group"><label class="form-label">DB Host</label>
          <input class="form-control" name="host" value="<?php echo htmlspecialchars($in['host']); ?>" /></div>
        <div class="form-group"><label class="form-label">DB Port</label>
          <input class="form-control" name="port" value="<?php echo htmlspecialchars($in['port']); ?>" /></div>
        <div class="form-group"><label class="form-label">DB Name</label>
          <input class="form-control" name="name" value="<?php echo htmlspecialchars($in['name']); ?>" placeholder="u123456788_bmet" /></div>
        <div class="form-group"><label class="form-label">DB User</label>
          <input class="form-control" name="user" value="<?php echo htmlspecialchars($in['user']); ?>" placeholder="u123456788_admin" /></div>
        <div class="form-group"><label class="form-label">DB Password</label>
          <input class="form-control" type="password" name="pass" value="" autocomplete="new-password" /></div>
      </div>
    </div>

    <div class="adm-card">
      <h2>2 · Administrator account</h2>
      <p class="adm-sub">Used to log in at <code>/admin/</code>.</p>
      <div class="form-grid">
        <div class="form-group"><label class="form-label">Username</label>
          <input class="form-control" name="admin_user" value="<?php echo htmlspecialchars($in['admin_user']); ?>" /></div>
        <div class="form-group"><label class="form-label">Email (optional)</label>
          <input class="form-control" type="email" name="admin_email" value="<?php echo htmlspecialchars($in['admin_email']); ?>" /></div>
        <div class="form-group"><label class="form-label">Password</label>
          <input class="form-control" type="password" name="admin_pass" autocomplete="new-password" /></div>
        <div class="form-group"><label class="form-label">Repeat password</label>
          <input class="form-control" type="password" name="admin_pass2" autocomplete="new-password" /></div>
      </div>
    </div>

    <div class="adm-card">
      <h2>3 · Site URL</h2>
      <p class="adm-sub">Base URL used inside QR codes on the printed cards. Leave empty to auto-detect (e.g. <code>https://yourdomain.com</code>).</p>
      <div class="form-group"><input class="form-control" name="base_url" value="<?php echo htmlspecialchars($in['base_url']); ?>" placeholder="https://yourdomain.com" /></div>
      <p class="hint mt">Detected now: <b><?php
        $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
        echo htmlspecialchars($scheme . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/install.php')), '/'));
      ?></b></p>
      <p class="mt"><button class="btn btn-primary btn-block" type="submit"><i class="fas fa-rocket"></i> Install now</button></p>
    </div>
  </form>
<?php endif; ?>

</div>
<div class="adm-foot">BMET EC Card Manager installer</div>
</body>
</html>
